export const allowedBlockNames = [
  "core/template-part",
  "core/pattern",
  "core/group",
  "core/columns",
  "core/column",
  "core/cover",
  "core/heading",
  "core/paragraph",
  "core/buttons",
  "core/button",
  "core/separator",
  "core/spacer",
  "core/query",
  "core/post-template",
  "core/post-title",
  "core/post-featured-image",
  "core/post-excerpt",
  "core/post-date",
  "core/query-pagination",
  "core/query-pagination-previous",
  "core/query-pagination-numbers",
  "core/query-pagination-next",
  "core/query-no-results",
  "core/post-content",
  "core/site-title",
  "core/site-tagline",
  "core/navigation",
  "core/home-link",
  "core/page-list",
] as const;

export type AllowedBlockName = (typeof allowedBlockNames)[number];
export const allowedBlockNameSet = new Set<string>(allowedBlockNames);
